In [23]:
import numpy as np

In [47]:
X = np.arange(9).reshape(3,3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
C = np.dot(X.T, X)
print(C)

[[45 54 63]
 [54 66 78]
 [63 78 93]]


In [57]:
# eigendecomposition

Covariance_M = 1/(3-1) * C
eigen_vals, eigen_vecs = np.linalg.eig(Covariance_M)

print(eigen_vals)
print(eigen_vecs)

[1.01199602e+02 8.00398408e-01 4.30393933e-15]
[[-0.4663281  -0.78477477  0.40824829]
 [-0.57099079 -0.08545673 -0.81649658]
 [-0.67565348  0.61386131  0.40824829]]


In [50]:
# svd

U, Sigma, VT = np.linalg.svd(X)

print(Sigma)
print(VT)
print(U)

[1.42267074e+01 1.26522599e+00 4.97902781e-16]
[[-0.4663281  -0.57099079 -0.67565348]
 [-0.78477477 -0.08545673  0.61386131]
 [-0.40824829  0.81649658 -0.40824829]]
[[-0.13511895  0.90281571  0.40824829]
 [-0.49633514  0.29493179 -0.81649658]
 [-0.85755134 -0.31295213  0.40824829]]


In [54]:
s = np.diag(Sigma)
print(s)
test = np.dot(U, np.dot(s, VT))
print(test)

[[1.42267074e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.26522599e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.97902781e-16]]
[[2.02013888e-16 1.00000000e+00 2.00000000e+00]
 [3.00000000e+00 4.00000000e+00 5.00000000e+00]
 [6.00000000e+00 7.00000000e+00 8.00000000e+00]]


In [63]:
print(np.square(Sigma)/2)
print(eigen_vals)

[1.01199602e+02 8.00398408e-01 1.23953589e-31]
[1.01199602e+02 8.00398408e-01 4.30393933e-15]


In [64]:
a = np.arange(24).reshape(3,8)

In [65]:
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [66]:
b = np.array([3,4,5,6,7,8,9,0])

In [67]:
print(b)

[3 4 5 6 7 8 9 0]


In [68]:
print(b.shape)

(8,)


In [69]:
a-b

array([[-3, -3, -3, -3, -3, -3, -3,  7],
       [ 5,  5,  5,  5,  5,  5,  5, 15],
       [13, 13, 13, 13, 13, 13, 13, 23]])

In [1]:
import torch

In [5]:
a = torch.Tensor(5)

In [6]:
print(a)

tensor([8.9082e-39, 9.9184e-39, 8.7245e-39, 1.0194e-38, 9.6429e-39])


In [7]:
a = torch.Tensor([5])

In [8]:
a

tensor([5.])

In [9]:
a.numpy()

array([5.], dtype=float32)

In [14]:
import numpy as np
one_hot = (np.arange(10)==a.numpy())

In [15]:
print(one_hot)

[False False False False False  True False False False False]


In [16]:
y = np.array([3,4,5,6,7])

In [17]:
y

array([3, 4, 5, 6, 7])

In [18]:
y.dtype

dtype('int32')

In [19]:
a = np.arange(25).reshape(5,5)

In [20]:
a[0]

array([0, 1, 2, 3, 4])

In [ ]:
    def train_net(self, X_train, y_train, epochs=1, batchSize=50):
        """ ==========
        YOUR CODE HERE
        ========== """
            
        X_train =  torch.FloatTensor(X_train)
        one_hot_y = np.zeros((y_train.shape[0], 10))
        for i in range(y_train.shape[0]):
            one_hot_y[i, int(y_train[i])] = 1.0
        one_hot_y_train =  torch.FloatTensor(one_hot_y)
        
        self.loss_fn = torch.nn.MSELoss(reduction='sum')
        self.optimizer = torch.optim.SGD(self.parameters(), lr=1e-8, momentum=0.9)
        
        loop = 0
        print(X_train.size())
        print(one_hot_y_train.size())
        for data,label in DataBatch(X_train,one_hot_y_train,batchSize,shuffle=False):
            print(self.weight1)
            for i in range(epochs):
                pred = self.forward(data[i])
                print(pred)
                print(label[i,None])
                loss = self.loss_fn(pred, label[i,None])
                # Backpropagation
                self.optimizer.zero_grad()
                loss.backward()
                self.optimizer.step()
            loop+=1
            
            if(loop ==epochs):
                break
        